### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by huangrkul** [SuperRonanCraft/AdvancedCustomMenu#25] opened 2018-05-30 21:09 UTC
**Plugin Version**:
advancedcustommenu v3.4.0

server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

spigot 
**Issue Type**:
Commands not working. (but sound does)

**Error**:
no error reporting.  Debugger is turned on.  Nothing in console.  I'm also doing everything in OP, so there shouldn't be any permission issue (?)

**Comments/More info**:
![screen shot 2018-05-30 at 2 04 49 pm](https://user-images.githubusercontent.com/39746374/40747542-79035532-6412-11e8-9763-097b2232ccc7.png)

Attached is my config.  Everything else seems to work.  Whenever I click on the item in the gui, my character's hand moves as if it's responding to it and the sound plays.  The only thing that doesn't work is the command itself.  I tried 'player:' 'console:' and 'op:' but still got nothing.  I also tried the Tech.yml menu and the command there doesn't work as well.  (the delay message works though)

I thought maybe it had to do with other conflicting plugins, so I literally stripped out everything else and left with just advancedcustommenu and its api jar.  Still didn't work.  I am happy to cooperate with you to get to the bottom of it, please take a look.  Thanks!

Will

**Comment by SuperRonanCraft** [comment] 2018-05-30 21:57
Mhh, I thought something was going on with command, umm, I think I blocked that error from appearing, looks like it came back to haunt me, I'ma have a long look at what the issue is, all I know right now is that the issue is localized and I know where it is, just not WHY 0-0

**Comment by huangrkul** [comment] 2018-05-30 22:13
Thank you for looking into it Ronan!

**Comment by SuperRonanCraft** [comment] 2018-05-31 02:22
Try and see if the issue is fixed, let me know here so I can close the issue, hopefully it was an easy-ish fix ;)

**Comment by huangrkul** [comment] 2018-05-31 03:11
I'll get right on it!  Thanks!

**Comment by huangrkul** [comment] 2018-05-31 03:22
Unfortunately, still doesn't work.  (tried both my own menu and the tech.yml menu provided)
here is console log.  The only differentiation from previous version (3.4.0) is that the console prints out the messages twice.

30.05 20:19:57 [Server] INFO - "Items" in click handler "1" for the item "Abilities", resulting in "[null]"
30.05 20:19:57 [Server] INFO - "Sound" in click handler "1" for the item "Abilities", resulting in "BLOCK_STONE_BUTTON_CLICK_ON, BLOCK_STONE_BUTTON_CLICK_ON, BLOCK_STONE_BUTTON_CLICK_ON"
30.05 20:19:57 [Server] INFO - "Click-Type" in click handler "1" for the item "Abilities", resulting in "[left]"
30.05 20:19:57 [Server] INFO - "Shift" in click handler "1" for the item "Abilities", resulting in "false"
30.05 20:19:57 [Server] INFO - "Commands" in click handler "1" for the item "Abilities", resulting in "1 Commands"
30.05 20:19:57 [Server] INFO The menu "mainmenu" has registered...
30.05 20:19:57 [Server] INFO - "Items" in click handler "1" for the item "Broadcast", resulting in "[null]"
30.05 20:19:57 [Server] INFO - "Permission" in click handler "1" for the item "Broadcast", resulting in "[example.savage]"
30.05 20:19:57 [Server] INFO - "Points" in click handler "1" for the item "Broadcast", resulting in "10"
30.05 20:19:57 [Server] INFO - "Price" in click handler "1" for the item "Broadcast", resulting in "10"
30.05 20:19:57 [Server] INFO - "Click-Type" in click handler "1" for the item "Broadcast", resulting in "[left]"
30.05 20:19:57 [Server] INFO - "Shift" in click handler "1" for the item "Broadcast", resulting in "false"
30.05 20:19:57 [Server] INFO - "Commands" in click handler "1" for the item "Broadcast", resulting in "1 Commands"
30.05 20:19:57 [Server] INFO The menu "Example" has registered...
30.05 20:19:57 [Server] INFO - "Items" in click handler "1" for the item "Delay", resulting in "[null]"
30.05 20:19:57 [Server] INFO - "Delay" in click handler "1" for the item "Delay", resulting in "20"
30.05 20:19:57 [Server] INFO - "Commands" in click handler "1" for the item "Delay", resulting in "1 Commands"
30.05 20:19:57 [Server] INFO The menu "Tech" has registered...
30.05 20:19:57 [Server] INFO - "Items" in click handler "1" for the item "Abilities", resulting in "[null]"
30.05 20:19:57 [Server] INFO - "Sound" in click handler "1" for the item "Abilities", resulting in "BLOCK_STONE_BUTTON_CLICK_ON, BLOCK_STONE_BUTTON_CLICK_ON, BLOCK_STONE_BUTTON_CLICK_ON"
30.05 20:19:57 [Server] INFO - "Click-Type" in click handler "1" for the item "Abilities", resulting in "[left]"
30.05 20:19:57 [Server] INFO - "Shift" in click handler "1" for the item "Abilities", resulting in "false"
30.05 20:19:57 [Server] INFO - "Commands" in click handler "1" for the item "Abilities", resulting in "1 Commands"
30.05 20:19:57 [Server] INFO The menu "mainmenu" has registered...
30.05 20:19:57 [Server] INFO - "Items" in click handler "1" for the item "Broadcast", resulting in "[null]"
30.05 20:19:57 [Server] INFO - "Permission" in click handler "1" for the item "Broadcast", resulting in "[example.savage]"
30.05 20:19:57 [Server] INFO - "Points" in click handler "1" for the item "Broadcast", resulting in "10"
30.05 20:19:57 [Server] INFO - "Price" in click handler "1" for the item "Broadcast", resulting in "10"
30.05 20:19:57 [Server] INFO - "Click-Type" in click handler "1" for the item "Broadcast", resulting in "[left]"
30.05 20:19:57 [Server] INFO - "Shift" in click handler "1" for the item "Broadcast", resulting in "false"
30.05 20:19:57 [Server] INFO - "Commands" in click handler "1" for the item "Broadcast", resulting in "1 Commands"
30.05 20:19:57 [Server] INFO The menu "Example" has registered...
30.05 20:19:57 [Server] INFO - "Items" in click handler "1" for the item "Delay", resulting in "[null]"
30.05 20:19:57 [Server] INFO - "Delay" in click handler "1" for the item "Delay", resulting in "20"
30.05 20:19:57 [Server] INFO - "Commands" in click handler "1" for the item "Delay", resulting in "1 Commands"
30.05 20:19:57 [Server] INFO The menu "Tech" has registered...
30.05 20:19:57 [Server] INFO Enabling AdvancedCustomMenu v3.4.1
30.05 20:19:57 [Server] INFO -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

**Comment by huangrkul** [comment] 2018-06-01 14:05
Yeah, in the console log, if you look at the last line on my post, it says 
30.05 20:19:57 [Server] INFO Enabling AdvancedCustomMenu v3.4.1

Sorry I couldn't help much :/

**Comment by SuperRonanCraft** [comment] 2018-06-01 14:40
Ahh, I see, alright. Are you replacing the commands with actually working commands? If they don't try other commands and if it still didn't work get me a copy of your files so I can trouble shoot

**Comment by huangrkul** [comment] 2018-06-01 18:34
Yeah I tried it again with vanilla commands, didn't work.  Here are my files~
[AdvancedCustomMenu.zip](https://github.com/SuperRonanCraft/AdvancedCustomMenu/files/2063763/AdvancedCustomMenu.zip)

Thanks again for the effort!

**Comment by SuperRonanCraft** [comment] 2018-06-02 19:31
So question, are you using a spigot build, or a Bukkit build?

**Comment by SuperRonanCraft** [comment] 2018-06-02 19:34
WAIT, are you trying to open the Example menu with the item?

**Comment by huangrkul** [comment] 2018-06-02 19:40
Negative.  the example menu doesn't show up and I think that was intentional.  I was able to open mainmenu.yml and tech.yml.  The menus do open correctly as well as every config in them minus the ability to trigger commands.

Thanks!

**Comment by SuperRonanCraft** [comment] 2018-06-02 20:59
Ohhhhhh, I found the issue. lol, it has to do with experience, um, try using a sub 3.4 version for now, i will get this fixed asap :)

**Comment by huangrkul** [comment] 2018-06-02 21:47
Nice!! Thanks Ronan!

**Comment by huangrkul** [comment] 2018-06-03 03:36
Hey Ronan, saw your new 3.4.2 patch and downloaded.  IT'S WORKING!!  

Thanks for fixing the bug.

**Comment by SuperRonanCraft** [comment] 2018-06-03 07:03
Awesome! Glad to hear, you helped me find out a lot of bugs, so not just this btw xD

**Closed by SuperRonanCraft** 2018-06-03 07:03 UTC
