### ISSUE TITLE
Error in Example menu 

### ISSUE THREAD

**Issue by TheTopCze** [SuperRonanCraft/AdvancedCustomMenu#1] opened 2017-10-20 18:44 UTC
Hello I use the latest spigot, but the problem is that the plugin is probably not supported with this version and will write me error

Conzole at server startup:

> Enabling AdvancedCustomMenu v1.1.0  Error occurred while enabling AdvancedCustomMenu v1.1.0 (Is it up to date?) 
> java.lang.NullPointerException: null 
> at me.SuperRonanCraft.AdvancedCustomMenu.references.Econ.registerEconomy(Econ.java:37) ~[?:?] 
> at me.SuperRonanCraft.AdvancedCustomMenu.references.Econ.(Econ.java:17) ~[?:?] 
> at me.SuperRonanCraft.AdvancedCustomMenu.Main.registerDependencies(Main.java:103) ~[?:?] 
> at me.SuperRonanCraft.AdvancedCustomMenu.Main.onEnable(Main.java:45) ~[?:?] 
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-93e20b3-31d3159] 
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-93e20b3-31d3159] 
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Spigot-93e20b3-31d3159] 
> at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [server.jar:git-Spigot-93e20b3-31d3159] 
> at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [server.jar:git-Spigot-93e20b3-31d3159] 
> at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-93e20b3-31d3159] 
> at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-93e20b3-31d3159] 
> at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-93e20b3-31d3159] 
> at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-93e20b3-31d3159] 
> at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-93e20b3-31d3159] 
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144] 

please repair

**Comment by SuperRonanCraft** [comment] 2017-10-20 18:48
Do you happen to have Vault installed without an economy plugin? Just curious, so I know the reason for the error :)

**Comment by TheTopCze** [comment] 2017-10-20 18:58
well, I installed saneeconomy. But when I want to open the menu, I still can not do it, and I'm currently in the console with this error.

> TheTopCz issued server command: /advancedcustommenu open Example 
>[2K [20:55:03 ERROR]: null 
org.bukkit.command.CommandException: Unhandled exception executing command 'advancedcustommenu' in plugin AdvancedCustomMenu v1.1.0 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-93e20b3-31d3159] 
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-93e20b3-31d3159] 
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-93e20b3-31d3159] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144] 
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-93e20b3-31d3159] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144] 
Caused by: java.lang.NullPointerException 
at me.SuperRonanCraft.AdvancedCustomMenu.references.Messages.colorPre(Messages.java:55) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.references.inv.Placeholders.placeholders(Placeholders.java:94) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.references.inv.Placeholders.checkPH(Placeholders.java:77) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.player.menus.inv.Inventories.createMenu(Inventories.java:82) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.player.Commands.open(Commands.java:45) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.player.Commands.CommandExecuted(Commands.java:27) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.Main.onCommand(Main.java:112) ~[?:?] 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-93e20b3-31d3159] 
... 15 more

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:05
Do you have the default config file, or did you edit/change them? This new error is coming from the plugin trying to get the prefix. But I ask again, do you have Vault installed?

**Comment by TheTopCze** [comment] 2017-10-20 19:11
Yes I have a vault, and files are default. http://prntscr.com/gzx533

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:12
Ohhh, I know what might be going on

**Comment by TheTopCze** [comment] 2017-10-20 19:13
Example.xml
`Title:
- '&a&lExample Frame #1'
- '&a&lExample Frame #2'
Frame-Delay: 20 ## Frame delay for the title
Rows: 6
Commands: 'ex; example'
Items:
  Broadcast:
    Slot: 1
    ## Amount of ticks to delay each frame
    Frame-Delay: 20 ## 20 by default if disabled or if delay equals 0
    Frames:
      1: ## At least one frame is needed!
        ## PlaceholderAPI is supported in every text section!
        Name: '&bHey there %player_name%' ## Required
        Item: 'anvil:2:4' ## Required
        Lore:
        - ''
        - '&7This is the first frame!'
      2:
        Name: '&aHey there %player_name%'
        Item: 'anvil:1:5'
        Lore:
        - ''
        - '&7This is the second frame!'
    Click-Handlers:
      1:
        Click-Type: 'left'## If disabled, click-type is ignored
        Shift: false ## If disabled, shift is ignored
        Commands:
        - 'broadcast &a%player_name% &cis a savage&f!'
        Price: 10 ## Must have vault and an economy plugin
        Price-Message: '%prefix% &cWhoops, looks like you need %price% to use this command!'
        Permission: 'example.savage'
        Permission-Message: '%prefix% &cLooks like you are not savage enough to use this command!'
  Wools:
    Slot: 2
    Frame-Delay: 20
    Frames:
      1:
        Name: '&cHey there %player_name%'
        Item: 'wool:1' ## <item>:[data]:[amount] (Supports placeholders)
        Lore:
        - ''
        - '&aThis is the first frame!'
      2:
        Name: '&bHey there %player_name%'
        Item: 'wool:3:2'
        Lore:
        - ''
        - '&bThis is the second frame!'
      3:
        Name: '&aHey there %player_name%'
        Item: 'wool:5:3'
        Lore:
        - ''
        - '&cThis is the third frame!'
  TextPlaceholders:
    Slot: 2
    Frame-Delay: 20
    Frames:
      1:
        Name: '&cHey there %player_name%'
        Item: 'wool:1' ## <item>:[data]:[amount] (Supports placeholders)
        Lore:
        - ''
        - '&aYou are within these coordinates! {cords:x1=200 x2=-200,z1=200 z2=-200,y1=50 y2=70}'
        - '&aYou are an epic player! {perm: donator.epic}'`

**Comment by TheTopCze** [comment] 2017-10-20 19:14
`Title:
- '&a&lExample Frame #1'
- '&a&lExample Frame #2'
Frame-Delay: 20 ## Frame delay for the title
Rows: 6
Commands: 'ex; example'
Items:
  Broadcast:
    Slot: 1
    ## Amount of ticks to delay each frame
    Frame-Delay: 20 ## 20 by default if disabled or if delay equals 0
    Frames:
      1: ## At least one frame is needed!
        ## PlaceholderAPI is supported in every text section!
        Name: '&bHey there %player_name%' ## Required
        Item: 'anvil:2:4' ## Required
        Lore:
        - ''
        - '&7This is the first frame!'
      2:
        Name: '&aHey there %player_name%'
        Item: 'anvil:1:5'
        Lore:
        - ''
        - '&7This is the second frame!'
    Click-Handlers:
      1:
        Click-Type: 'left'## If disabled, click-type is ignored
        Shift: false ## If disabled, shift is ignored
        Commands:
        - 'broadcast &a%player_name% &cis a savage&f!'
        Price: 10 ## Must have vault and an economy plugin
        Price-Message: '%prefix% &cWhoops, looks like you need %price% to use this command!'
        Permission: 'example.savage'
        Permission-Message: '%prefix% &cLooks like you are not savage enough to use this command!'
  Wools:
    Slot: 2
    Frame-Delay: 20
    Frames:
      1:
        Name: '&cHey there %player_name%'
        Item: 'wool:1' ## <item>:[data]:[amount] (Supports placeholders)
        Lore:
        - ''
        - '&aThis is the first frame!'
      2:
        Name: '&bHey there %player_name%'
        Item: 'wool:3:2'
        Lore:
        - ''
        - '&bThis is the second frame!'
      3:
        Name: '&aHey there %player_name%'
        Item: 'wool:5:3'
        Lore:
        - ''
        - '&cThis is the third frame!'
  TextPlaceholders:
    Slot: 2
    Frame-Delay: 20
    Frames:
      1:
        Name: '&cHey there %player_name%'
        Item: 'wool:1' ## <item>:[data]:[amount] (Supports placeholders)
        Lore:
        - ''
        - '&aYou are within these coordinates! {cords:x1=200 x2=-200,z1=200 z2=-200,y1=50 y2=70}'
        - '&aYou are an epic player! {perm: donator.epic}'`

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:14
Don't worry, it should be a quick fix, ima do a quick update on spigot in a minute here.

**Comment by TheTopCze** [comment] 2017-10-20 19:15
Ok, thank you!

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:15
Is TheTopCze, your spigot name?

**Comment by TheTopCze** [comment] 2017-10-20 19:16
Yes https://www.spigotmc.org/members/34622/

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:18
Try out the new version, hope it was as easy as I thought o-o

**Comment by TheTopCze** [comment] 2017-10-20 19:26
I used a new version of the menu still not displayed: 

>[2K [21:24:05 INFO]: TheTopCz issued server command: /advancedcustommenu open Example 
>[2K [21:24:05 ERROR]: null 
org.bukkit.command.CommandException: Unhandled exception executing command 'advancedcustommenu' in plugin AdvancedCustomMenu v1.1.1 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-93e20b3-31d3159] 
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-93e20b3-31d3159] 
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-93e20b3-31d3159] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144] 
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-93e20b3-31d3159] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-93e20b3-31d3159] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144] 
Caused by: java.lang.NullPointerException 
at me.SuperRonanCraft.AdvancedCustomMenu.references.Messages.colorPre(Messages.java:55) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.references.inv.Placeholders.placeholders(Placeholders.java:94) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.references.inv.Placeholders.checkPH(Placeholders.java:77) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.player.menus.inv.Inventories.createMenu(Inventories.java:82) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.player.Commands.open(Commands.java:45) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.player.Commands.CommandExecuted(Commands.java:27) ~[?:?] 
at me.SuperRonanCraft.AdvancedCustomMenu.Main.onCommand(Main.java:112) ~[?:?] 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-93e20b3-31d3159] 
... 15 more

**Comment by TheTopCze** [comment] 2017-10-20 19:28
This is shown in my inventory http://prntscr.com/gzxdfv

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:33
Do you know how you were able to get the item in your inventory?

**Comment by TheTopCze** [comment] 2017-10-20 19:35
After entering the command, it did not appear there after about 2 minutes, it started to jump in there

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:37
Did you leave the inventory by closing the menu, or did a command open something else up?

**Comment by TheTopCze** [comment] 2017-10-20 19:40
I apologize a little differently. If you enter a command, I put a wave in the inventory.

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:41
A wave? sorry, what do you mean?

**Comment by TheTopCze** [comment] 2017-10-20 19:42
wool

**Comment by SuperRonanCraft** [comment] 2017-10-20 19:43
The plugin commands, or the commands from the menu, or does that matter?

**Comment by TheTopCze** [comment] 2017-10-20 19:49
It does not matter that it works on menu, i from the console

**Comment by SuperRonanCraft** [comment] 2017-10-20 20:06
So i found out the error that is causing the plugin to not open up the menu, that will be fixed in a second, but I'm not seeing any items in my inventory, maybe that was caused by the issue with messages? Anyways, i'll get a new patch out here now, sorry for all the bugs btw, that's why it's good to have a bug report system, cause I can't physically test every situation :)

**Comment by TheTopCze** [comment] 2017-10-20 20:27
Yes! It works, Thanks your help

**Comment by SuperRonanCraft** [comment] 2017-10-20 21:14
Not a problem, new features coming soon, more with commands and some with a new "View-Handler" ;)

**Closed** 2017-10-21 01:07 UTC
Labels: bug
